// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitstop.BaggageSetManagementEventHandler.DataAccess;

namespace Pitstop.BaggageSetManagementEventHandler.Migrations
{
    [DbContext(typeof(BaggageSetManagementDBContext))]
    [Migration("20190521131909_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pitstop.BaggageSetManagement.Model.BaggageSet", b =>
                {
                    b.Property<Guid>("BaggageSetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaggageClaimId");

                    b.Property<bool>("DeliveredToBaggageClaim");

                    b.Property<bool>("LoadedOnFlight");

                    b.Property<string>("ScheduledFlightId");

                    b.HasKey("BaggageSetId");

                    b.ToTable("BaggageSet");
                });
#pragma warning restore 612, 618
        }
    }
}
