// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitstop.FlightPlanningManagementEventHandler.DataAccess;

namespace Pitstop.FlightPlanningManagementEventHandler.Migrations
{
    [DbContext(typeof(FlightPlanningManagementDBContext))]
    [Migration("20190521191455_newmigration")]
    partial class newmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pitstop.FlightPlanningManagementEventHandler.Model.CheckinCounter", b =>
                {
                    b.Property<int>("CheckInCounterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckInCounterName");

                    b.HasKey("CheckInCounterId");

                    b.ToTable("CheckinCounter");
                });

            modelBuilder.Entity("Pitstop.FlightPlanningManagementEventHandler.Model.Flight", b =>
                {
                    b.Property<string>("FlightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AirlineName");

                    b.Property<string>("Destination");

                    b.Property<string>("FlightNumber");

                    b.Property<string>("Origin");

                    b.HasKey("FlightId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Pitstop.FlightPlanningManagementEventHandler.Model.Gate", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("GateId");

                    b.ToTable("Gate");
                });

            modelBuilder.Entity("Pitstop.FlightPlanningManagementEventHandler.Model.ScheduledFlight", b =>
                {
                    b.Property<int>("ScheduledFlightId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CheckInCounterId");

                    b.Property<string>("FlightId");

                    b.Property<int?>("GateId");

                    b.Property<DateTime>("PlannedEndTime");

                    b.Property<DateTime>("PlannedStartTime");

                    b.HasKey("ScheduledFlightId");

                    b.HasIndex("CheckInCounterId");

                    b.HasIndex("FlightId");

                    b.HasIndex("GateId");

                    b.ToTable("ScheduledFlight");
                });

            modelBuilder.Entity("Pitstop.FlightPlanningManagementEventHandler.Model.ScheduledFlight", b =>
                {
                    b.HasOne("Pitstop.FlightPlanningManagementEventHandler.Model.CheckinCounter", "CheckInCounter")
                        .WithMany()
                        .HasForeignKey("CheckInCounterId");

                    b.HasOne("Pitstop.FlightPlanningManagementEventHandler.Model.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.HasOne("Pitstop.FlightPlanningManagementEventHandler.Model.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("GateId");
                });
#pragma warning restore 612, 618
        }
    }
}
