// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitstop.FlightManagement.DataAccess;

namespace Pitstop.FlightManagement.Migrations
{
    [DbContext(typeof(FlightManagementDBContext))]
    [Migration("20190521164706_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pitstop.FlightManagement.Model.Airline", b =>
                {
                    b.Property<string>("AirlineId");

                    b.Property<string>("FlightId");

                    b.Property<string>("Name");

                    b.HasKey("AirlineId", "FlightId");

                    b.HasIndex("FlightId")
                        .IsUnique();

                    b.ToTable("Airline");
                });

            modelBuilder.Entity("Pitstop.FlightManagement.Model.Flight", b =>
                {
                    b.Property<string>("FlightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Destination");

                    b.Property<string>("FlightNumber");

                    b.Property<string>("Origin");

                    b.HasKey("FlightId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Pitstop.FlightManagement.Model.Airline", b =>
                {
                    b.HasOne("Pitstop.FlightManagement.Model.Flight")
                        .WithOne("Airline")
                        .HasForeignKey("Pitstop.FlightManagement.Model.Airline", "FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
