// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitstop.FlightManagement.DataAccess;

namespace Pitstop.FlightManagement.Migrations
{
    [DbContext(typeof(FlightManagementDBContext))]
    [Migration("20190521131712_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pitstop.FlightManagement.Model.Airline", b =>
                {
                    b.Property<string>("AirlineId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("AirlineId");

                    b.ToTable("Airline");
                });

            modelBuilder.Entity("Pitstop.FlightManagement.Model.Flight", b =>
                {
                    b.Property<string>("FlightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AirlineId");

                    b.Property<string>("Destination");

                    b.Property<string>("FlightNumber");

                    b.Property<string>("Origin");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Pitstop.FlightManagement.Model.Flight", b =>
                {
                    b.HasOne("Pitstop.FlightManagement.Model.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId");
                });
#pragma warning restore 612, 618
        }
    }
}
