version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=DEBmbwkSrzy9D1T9cJfa

  sqlserverflightmanagement:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserverflightmanagement
    volumes:
      - sqlserverflightmanagementdata:/var/opt/mssql 
    ports:
      - "1439:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2
      
  sqlserverflightplanningmanagement:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserverflightplanningmanagement
    volumes:
      - sqlserverflightplanningmanagementdata:/var/opt/mssql 
    ports:
      - "1440:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

  sqlserverbaggage:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserverbaggage
    volumes:
      - baggagesetdata:/var/opt/mssql 
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2     

  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y 

  flightmanagementapi:
    image: pitstop/flightmanagementapi:latest
    build: FlightManagementAPI
    depends_on:
      - rabbitmq
      - sqlserverflightmanagement
    ports:
      - "5900"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  flightplanningmanagementapi:
    image: pitstop/flightplanningmanagementapi:latest
    build: FlightPlanningManagementAPI
    container_name: flightplanningmanagementapi
    depends_on:
      - rabbitmq
      - sqlserverflightplanningmanagement
    ports:
      - "5901"
    environment:
      - DOTNET_ENVIRONMENT=Production

  flightplanningmanagementeventhandler:
    image: pitstop/flightplanningmanagementeventhandler:latest
    build: FlightPlanningManagementEventHandler
    container_name: flightplanningmanagementeventhandler
    depends_on:
      - rabbitmq
      - sqlserverflightplanningmanagement
    environment:
      - DOTNET_ENVIRONMENT=Production

  baggagesetmanagementapi:
    image: pitstop/baggagesetmanagementapi:latest
    build: BaggageSetManagementAPI
    depends_on:
      - rabbitmq
      - sqlserverbaggage
    ports:
      - "5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production      

  auditlogservice:
    image: pitstop/auditlogservice:latest
    build: AuditlogService
    container_name: auditlogservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT=Production

  bordersecuritynotificationservice:
    image: pitstop/bordersecuritynotificationservice:latest
    build: BorderSecurityNotificationService
    container_name: bordersecuritynotificationservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT=Production

  timeservice:
    image: pitstop/timeservice:latest
    build: TimeService
    container_name: timeservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT=Production

  baggagesetmanagementeventhandler:
    image: pitstop/baggagemanagementeventhandler:latest
    build: BaggageSetManagementEventHandler
    container_name: baggagesetmanagementeventhandler
    depends_on:
      - rabbitmq
      - sqlserverbaggage
    environment:
      - DOTNET_ENVIRONMENT=Production    

volumes:
  sqlserverflightmanagementdata:
    external: true    
  sqlserverflightplanningmanagementdata:
    external: true  
  rabbitmqdata:
    external: true
  baggagesetdata:
    external: true   
