# Use this overide file when debugging.
# This override will expose the ports of the API services to the host
# which will enable you to access the API services directly from the browser.
# Do NOT start multiple instances of the API services when using this override 
# (this will cause port collisions).
version: '3'
services:

  flightmanagementapi:
    ports:
      - "5900:5900"

  flightplanningmanagementapi:
    ports:
      - "5901:5901"

  baggagesetmanagementapi:
    ports: 
      - "5001:5001"